using HamHub.Domain.Enums;

namespace HamHub.Application.QsoEntries.DTOs;

public record QsoDto(
    int Id,
    string UserId,
    DateTime DateUtc,
    string OwnCallsign,
    string WorkedCallsign,
    Band Band,
    double? Frequency,
    Mode Mode,
    string? RstSent,
    string? RstReceived,
    string? Submode,
    string? Locator,
    string? MyGridsquare,
    string? Country,
    int? Dxcc,
    string? Continent,
    string? State,
    int? CqZone,
    int? ItuZone,
    string? County,
    string? MyState,
    string? MyCounty,
    string? Iota,
    string? PotaRefs,
    string? SotaRefs,
    string? AwardRefs,
    string? Name,
    string? Qth,
    double? TxPower,
    string? Comment,
    string? QrzId,
    string? QrzConfirmationStatus,
    DateTime? QrzConfirmedAt,
    DateTime? QrzQslDate,
    DateTime? EqslSentAt,
    DateTime? EqslConfirmedAt,
    string? EqslLastResult,
    DateTime? LotwConfirmedAt,
    DateTime? LotwQslDate,
    string? LotwLastResult,
    DateTime CreatedAt,
    DateTime UpdatedAt
);
